<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <Version>$(AutoVersion)</Version>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWindowsForms>true</UseWindowsForms>
        <UseWpf>true</UseWpf>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
				<Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <InternalsVisibleTo Include="UnitTests" />
        <InternalsVisibleTo Include="IntegrationTests" />
        <InternalsVisibleTo Include="Benchmarks" />
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.CommandLine" Version="2.0.3" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
        <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.5.4" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="System.Management.Automation" Version="7.5.4" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="AutoContracts">
            <HintPath>lib\AutoContracts.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
