<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="AutoContracts" Private="false">
            <HintPath>lib\AutoContracts.dll</HintPath>
        </Reference>
    </ItemGroup>

    <Target Name="DeployPlugin" AfterTargets="Build">
        <PropertyGroup>
            <PluginDir>$([System.Environment]::GetFolderPath(SpecialFolder.UserProfile))/.config/auto/plugins/$(AssemblyName)</PluginDir>
        </PropertyGroup>
        <ItemGroup>
            <PluginOutput Include="$(TargetDir)**\*" />
        </ItemGroup>
        <Copy SourceFiles="@(PluginOutput)" DestinationFiles="@(PluginOutput->'$(PluginDir)/%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    </Target>

    <ItemGroup>
        <None Update="plugin.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
